/**
 * Fun splash texts to show while fetching PR information
 */
const SPLASH_TEXTS = [
  "Reticulating splines...",
  "Composing symphonies of code...",
  "Herding cats...",
  "Dividing by zero...",
  "Spinning up hamster wheels...",
  "Consulting the Oracle...",
  "Brewing artisanal electrons...",
  "Polishing pixels...",
  "Untangling spaghetti code...",
  "Channeling the spirits of merged PRs...",
  "Decoding developer hieroglyphics...",
  "Summoning code reviewers...",
  "Interrogating the API...",
  "Counting sheep... I mean commits...",
  "Negotiating with rate limits...",
  "Compiling excuses...",
  "Defragmenting memories...",
  "Calibrating flux capacitors...",
  "Initializing coffee protocols...",
  "Downloading more RAM...",
  "Optimizing rubber ducks...",
  "Consulting Stack Overflow...",
  "Reading tea leaves...",
  "Aligning chakras...",
  "Bribing the database...",
  "Teaching rocks to think...",
  "Wrangling wild pointers...",
  "Refactoring the universe...",
  "Persuading servers to cooperate...",
  "Chasing race conditions...",
  "Debugging quantum states...",
  "Inflating balloons...",
  "Tickling transistors...",
  "Massaging metadata...",
  "Convincing APIs to share...",
  "Pleading with parsers...",
  "Bribing bits and bytes...",
  "Soothing angry exceptions...",
  "Whispering to webhooks...",
  "Juggling JSON...",
  "Interpreting smoke signals...",
  "Calculating infinity...",
  "Reversing entropy...",
  "Taming wild threads...",
  "Negotiating with null pointers...",
  "Sweeping stack traces...",
  "Feeding the code monkeys...",
  "Charging the flux capacitor...",
  "Crystallizing logic...",
  "Deduplicating duplicates...",
  "Obfuscating obfuscation...",
  "Fragmenting fragments...",
  "Compressing decompression...",
  "Sorting chaos...",
  "Indexing the void...",
  "Parsing the unparseable...",
  "Validating validators...",
  "Caching cache misses...",
  "Garbage collecting garbage...",
  "Synchronizing asynchronicity...",
  "Debugging the debugger...",
  "Profiling the profiler...",
  "Benchmarking benchmarks...",
  "Testing the tests...",
  "Mocking the mockers...",
  "Stubbing stubs...",
  "Asserting assertions...",
  "Awaiting the awaited...",
  "Promising promises...",
  "Observing observers...",
  "Decorating decorators...",
  "Factoring factories...",
  "Adapting adapters...",
  "Proxying proxies...",
  "Bridging bridges...",
  "Chaining chains...",
  "Piping pipelines...",
  "Streaming streams...",
  "Buffering buffers...",
  "Queuing queues...",
  "Stacking stacks...",
  "Heaping heaps...",
  "Mapping maps...",
  "Setting sets...",
  "Listing lists...",
  "Arraying arrays...",
  "Objectifying objects...",
  "Stringing strings...",
  "Numbering numbers...",
  "Booleaning booleans...",
  "Nullifying nulls...",
  "Undefining undefineds...",
  "Typing types...",
  "Interfacing interfaces...",
  "Classing classes...",
  "Moduling modules...",
  "Packaging packages...",
  "Depending dependencies...",
  "Versioning versions...",
  "Tagging tags...",
  "Branching branches...",
  "Merging merges...",
  "Committing commits...",
  "Pushing pushes...",
  "Pulling pulls...",
  // Extra bonus splash texts
  "Architecting architectures...",
  "Containerizing containers...",
  "Orchestrating orchestrators...",
  "Microservicing microservices...",
  "Serverless-ing serverless...",
  "Clouding clouds...",
  "DevOps-ing DevOps...",
  "Agile-ing agility...",
  "Scrum-ing scrums...",
  "Sprint-ing sprints...",
  "Standup-ing standups...",
  "Retro-ing retrospectives...",
  "Demo-ing demos...",
  "Deploying deployments...",
  "Rolling back rollbacks...",
  "Hotfixing hotfixes...",
  "Patching patches...",
  "Releasing releases...",
  "Staging staging environments...",
  "Production-ing production...",
  "Monitoring monitors...",
  "Alerting alerts...",
  "Logging loggers...",
  "Tracing tracers...",
  "Metering metrics...",
  "Graphing graphs...",
  "Dashing dashboards...",
  "Incidenting incidents...",
  "Postmortem-ing postmortems...",
  "Escalating escalations...",
  "Ticketing tickets...",
  "Slacking Slack messages...",
  "Emailing emails...",
  "Meeting-ing meetings...",
  "Calendaring calendars...",
  "Scheduling schedules...",
  "Planning plans...",
  "Estimating estimates...",
  "Pointing story points...",
  "Backlogging backlogs...",
  "Prioritizing priorities...",
  "Roadmapping roadmaps...",
  "Visioning visions...",
  "Strategizing strategies...",
  "Pivoting pivots...",
  "Iterating iterations...",
  "Shipping ships...",
  "Launching launches...",
];

/**
 * Get a random splash text, avoiding recent duplicates
 */
const recentTexts: string[] = [];
export function getRandomSplashText(): string {
  // Get texts that haven't been shown recently
  const availableTexts = SPLASH_TEXTS.filter((text) => !recentTexts.includes(text));
  const pool = availableTexts.length > 0 ? availableTexts : SPLASH_TEXTS;

  const index = Math.floor(Math.random() * pool.length);
  const selected = pool[index] as string;

  // Track recent texts (keep last 10)
  recentTexts.push(selected);
  if (recentTexts.length > 10) {
    recentTexts.shift();
  }

  return selected;
}
